### ISSUE TITLE
Output to TypeScript?

### ISSUE THREAD

**Issue by radicand** [apollographql/graphql-document-collector#13]
Is there any chance of being able to output to a TypeScript file instead of a JSON file? I like this functionality, but importing JSON into TypeScript is hackish at best and doesn't provide any compile-time sanity checks (or code completion). Thanks!

**Comment by stubailo** [comment]
Wow, that's quite silly that TS doesn't support that, since Node allows you to import `.json` files natively. What are you using the output from this tool for? Curious what the end goal is so we can select the right solution without complicating the tool.

**Comment by radicand** [comment]
Thanks - I'm using this so I can write my queries in separate `.graphql` files, but still include them sanely in my composed component:

```ts
export default compose(
  ...other things
  graphql(GQLQueries['src/queries/thisParticularQuery.graphql']),
)(MyComponent);
```

What I've done in the meantime is post-process the generated JSON crudely into a TypeScript wrapper:

```js
// queryjson2ts.js
const fs = require('fs');

const queriesJSON = require('./src/queries/queries.json');

const data = `const queries: { [key: string]: any } = ${JSON.stringify(
  queriesJSON,
  null,
  2,
)};\n\nexport default queries;`;
fs.writeFileSync('./src/queries/queries.ts', data);
```

From this, I can then do a normal TypeScript import: `import GQLQueries from '../../queries/queries';` and use it as seen above.

This is working for me for now, but it would be nice to someday drop this extra step and have it generate directly to a TS or JS module instead of just JSON.

**Comment by stephen** [comment]
@radicand are you trying to import the query documents in a webpack/bundler environment?

We previously did a similar thing at @samsarahq, but then switched to a [`webpack loader`](https://github.com/stephen/graphql-loader) for this purpose.

Then you can do something like:
```tsx
// component.ts
import QueryDocument from "client/page/something.graphql";

export default compose(
  ...other things
  graphql(GQLQueries['src/queries/thisParticularQuery.graphql']),
)(MyComponent);

// declare.d.ts - make it nicely typed
declare module "*.graphql" {
  import { DocumentNode } from "graphql";
  const dummyDocument: DocumentNode;
  export default dummyDocument;
}
```

If it's in a different/node environment, maybe there's something else we can do here..

**Comment by radicand** [comment]
Thanks @stephen, I do have webpack in my tooling, and will give your example a shot. Given the possibility of this, and the workaround I have in place, I'm going to close the issue.
