### ISSUE TITLE
Handling Inline Fragments?

### ISSUE THREAD

**Issue by ekron** [apollographql/graphql-document-collector#17]
Hello, thanks for this useful module.

Say I have a query with an inline fragment in it:

```graphql
query ListMovies {
  allFilms {
    films {
      ...on Thing {
        ...Movie
      }
    }
  }
}
```

Once processed, I'd expect the `ListMovies`to have 3 definitions. 

- One for the query, 
- one for the `Movie` fragment and 
- one for the `Place` fragment used in `Movie`.

Here's a test:

```ts
it('should resolve all Inline fragments', () => {
      return loadGlob(
        path.join(__dirname, '..', '..', '..', 'inlineFragmentExample'),
        '**/*.graphql'
      )
      .then((root: DocumentDirectory) => {
        const fMap = createFragmentMap(root);
        const origDoc = root.directories[1].documents[0];
        const transformedDoc = addFragmentsToDocument(origDoc, fMap);
        assert.equal(transformedDoc.definitions.length, 3);
      });
    });
```

But the `ListMovies` document will only have one definition:

- One for the query.

I *think* the problem is that `fragmentSpreadsInSelectionSet` in `src/transforms/resolveFragments.ts` doesn't seem to handle the case of inline fragments (e.g. `... on Thing`).

E.g. The fix would be:

```ts
else if ((sel.kind === 'InlineFragment')) {
      fragmentSpreadsInSelectionSet((sel as InlineFragmentNode).selectionSet, fMap, fragmentSpreads);
    }
```

Then the test will pass.

If this make senses as a fix I can send you a pull request.

Thanks for reading.

**Comment by stephen** [comment]
Thanks! This was fixed in 0.2.2.
