### ISSUE TITLE
Fragments in the same document as the query will be imported twice

### ISSUE THREAD

**Issue by rricard** [apollographql/graphql-document-collector#4]
This will make fail an actual query due to fragment duplication. This should be fixed ASAP.

Example:

This document

**Test.graphql**
```graphql
querry Test {
  test {
    ...TestFragment
  }
}

fragment TestFragment {
  testString
}
```

will compile to an equivalent of:

```graphql
querry Test {
  test {
    ...TestFragment
  }
}

fragment TestFragment {
  testString
}

fragment TestFragment {
  testString
}
```

A workaround to this is to put one fragment or operation per file and not one more!

See the [resolve fragments](https://github.com/apollostack/graphql-document-collector/blob/master/src/transforms/resolveFragments.ts) transform to fix this.

**Comment by stephen** [comment]
Fixed in #14.
